default: &default
  adapter: mysql2
  encoding: utf8
  # charset: utf8mb4
  # collation: utf8mb4_unicode_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  socket: /tmp/mysql.sock
  host: db

development:
  <<: *default
  database: biita!_development
  username: root
  password: password

test:
  <<: *default
  database: biita_test

production:
  <<: *default
  database: biita!_production
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock
